// https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Maven+Plugin
node{
  stage ('Build') {
 
    git ([url: 'http://172.17.4.50:10080/root/osev3-examples', branch: 'cicd'])
     
    def mvnHome = tool 'M3'
    def gradleHome = tool 'G3'

    // sh "cd spring-boot/sample-microservices-springboot && ${mvnHome}/bin/mvn clean install"

    sh "cd spring-boot/sample-microservices-springboot && ${gradleHome}/gradle-3.5/bin/gradle build uploadArchives"

  }
}
