// https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Maven+Plugin
node{
  stage ('Build') {
 
    git url: 'http://172.17.4.50:10080/root/osev3-examples'
    
    dir 'spring-boot/sample-microservices-springboot/'
 
    withMaven(
        // Maven installation declared in the Jenkins "Global Tool Configuration"
        maven: 'M3',
        // Maven settings.xml file defined with the Jenkins Config File Provider Plugin
        // Maven settings and global settings can also be defined in Jenkins Global Tools Configuration
        // mavenSettingsConfig: 'my-maven-settings',
        // mavenLocalRepo: '.repository'
        ) {
 
      // Run the maven build
      sh "mvn clean install"
 
    } // withMaven will discover the generated Maven artifacts, JUnit Surefire & FailSafe reports and FindBugs reports
  }
}
